one_lanes = [
    ("halal_meat", "dunkin"),
    ("dnp", "bike_ent"),
    ("pulis_agu", "pera_mpc"),
    ("pera_mpc", "learnfast"),
    ("coop_fuel", "tambacan"),
    ("tambacan","coop_fuel"),
    ("tambacan", "bdo_network"),
    ("bdo_network","tambacan"),
    ("gaisano_old","pub_market"),
    ("gaisano_old","ukay_market"),
    ("nehal_arc","iligan_pier"),
    ("desmark","fire_safe"),
    ("fire_safe","desmark"),
    ("pnb","daily"),
    ("daily","pnb"),
    ("emcor","uncle_brew"),
    ("uncle_brew","emcor"),
    ("icnhs","petron"),
    ("petron","icnhs"),
    ("orix","deja_teu"),
    ("deja_teu","orix"),
    ("meat_shop","sym"),
    ("meat_shop","min_burger"),
    ("min_burger","meat_shop"),
    ("palao_mrkt","mottrad_villa"),
    ("palao_mrkt","iligan_deal"),
    ("iligan_deal","palao_mrkt"),
    ("learnfast","glo_flash"),
    ("glo_flash","learnfast"),
    ("mc_hotel", "learnfast"),
    ("learnfast","mc_hotel"),
    ("glo_flash","pop_rock"),
    ("doc_uy","pop_rock"),
    ("fire_safe", "pnb"),
    ("pnb","fire_safe"),
    ("megatech","min_burger"),
    ("min_burger","megatech"),
    ("iligan_deal","phoenix_lpg"),
    ("phoenix_lpg","iligan_deal"),
    ("mot_race","fount_acad"),
    ("fount_acad","mot_race"),
    ("shoppe_24","ortiz"),
    ("ortiz","shoppe_24"),
    ("sapp_ara","icnhs"),
    ("icnhs","sapp_ara"),
    ("coinsaver","phoenix_gas"),
    ("phoenix_gas","coinsaver"),
    ("puregold","comelec"),
    ("comelec","puregold"),
    ("pc_ilgn","phoenix_lpg"),
    ("phoenix_lpg","pc_ilgn"),
    ("bdo_network","landbank"),
    ("landbank","bdo_network"),
    ("post_off","epson"),
    ("epson","post_off"),
    ("uncle_brew","emcor"),
    ("emcor","uncle_brew"),
]

two_lanes = [
    ("coop_fuel","tc_circle"),
    ("tc_circle","coop_fuel"),
    ("ncip","icnhs"),
    ("icnhs", "ncip"),
    ("tc_circle","iligan_pier"),
    ("iligan_pier","tc_circle"),
    ("landbank","gaisano_old"),
    ("gaisano_old","landbank"),
    ("petron","coop_fuel"),
    ("coop_fuel","petron"),
    ("ball_4k","cq_print"),
    ("ortiz","citi_alley"),
    ("citi_alley","tomntoms"),
    ("zoey","gsis")
]

three_lanes = [
    ("pub_market","mejia_bldg"),
    ("gaisano_mall","ncip"),
    ("ncip","gaisano_mall"),
    ("tc_circle","gaisano_old"),
    ("gaisano_old","tc_circle")
]

four_lanes = [
    ("mejia_bldg","meatshop")
]

