one_lanes = [
    ("coop_fuel","octagon"),
    ("octagon","coop_fuel"),
    ("octagon","penshoppe"),
    ("penshoppe","octagon"),
    ("penshoppe","pater"),
    ("pater","penshoppe")
    ("pater","glo_flash")
    ("glo_flash","pater")
    ("glo_flash", "tambacan"),
    ("tambacan","glo_flash"),
    ("tambacan", "fount_acad"),
    ("fount_acad","tambacan"),
    ("fount_acad","gsis"),
    ("gsis","fount_acad"),
    ("gsis","qa_plaza"),
    ("qa_plaza","gsis"),
    ("qa_plaza","new_flash"),
    ("new_flash","qa_plaza"),
    ("new_flash","pondoc"),
    ("pondoc","new_flash"),
    ("pondoc","mayo_dia"),
    ("mayo_dia","pondoc"),
    ("mayo_dia","lanastida"),
    ("lanastida","mayo_dia"),
    ("lanastida","phoenix_gas"),
    ("phoenix_gas","lanastida"),
    ("phoenix_gas","palao_mrkt"),
    ("palao_mrkt","phoenix_gas"),
    ("palao_mrkt","puregold"),
    ("puregold","palao_mrkt"),
    ("puregold","coco_pet"),
    ("coco_pet","puregold"),
    ("coco_pet","pc_ilgn"),
    ("pc_ilgn","coco_pet"),
    ("pc_ilgn","bdo_network"),
    ("bdo_network","pc_ilgn"),
    ("desmark","fire_safe"),
    ("fire_safe","desmark"),


    ("halal_meat", "dunkin"),
    ("dnp", "bike_ent"),
    ("pulis_agu", "pera_mpc"),
    ("pera_mpc", "learnfast"),

    ("gaisano_old","pub_market"),
    ("gaisano_old","ukay_market"),
    ("nehal_arc","iligan_pier"),
    ("pnb","daily"),
    ("daily","pnb"),
    ("emcor","uncle_brew"),
    ("uncle_brew","emcor"),
    ("icnhs","petron"),
    ("petron","icnhs"),
    ("orix","deja_teu"),
    ("deja_teu","orix"),
    ("meat_shop","sym"),
    ("meat_shop","min_burger"),
    ("min_burger","meat_shop"),
    ("palao_mrkt","mottrad_villa"),
    ("palao_mrkt","iligan_deal"),
    ("iligan_deal","palao_mrkt"),
    ("learnfast","glo_flash"),
    ("glo_flash","learnfast"),
    ("mc_hotel", "learnfast"),
    ("learnfast","mc_hotel"),
    ("glo_flash","pop_rock"),
    ("doc_uy","pop_rock"),
    ("fire_safe", "pnb"),
    ("pnb","fire_safe"),
    ("megatech","min_burger"),
    ("min_burger","megatech"),
    ("iligan_deal","phoenix_lpg"),
    ("phoenix_lpg","iligan_deal"),
    ("mot_race","fount_acad"),
    ("fount_acad","mot_race"),
    ("shoppe_24","ortiz"),
    ("ortiz","shoppe_24"),
    ("sapp_ara","icnhs"),
    ("icnhs","sapp_ara"),
    ("coinsaver","phoenix_gas"),
    ("phoenix_gas","coinsaver"),
    ("puregold","comelec"),
    ("comelec","puregold"),
    ("pc_ilgn","phoenix_lpg"),
    ("phoenix_lpg","pc_ilgn"),
    ("bdo_network","landbank"),
    ("landbank","bdo_network"),
    ("post_off","epson"),
    ("epson","post_off"),
    ("uncle_brew","emcor"),
    ("emcor","uncle_brew"),
]

two_lanes = [
    ("petron", "vanitea"),
    ("vanitea", "petron"),
    ("petron","coop_fuel"),
    ("coop_fuel","petron"),
    ("coop_fuel","daily"),
    ("daily","coop_fuel"),
    ("daily","tc_circle"),
    ("tc_circle","daily"),
    ("tc_circle","iligan_pier"),
    ("iligan_pier","tc_circle"),
    ("petron", "uncle_brew"),
    ("uncle_brew","petron"),
    ("uncle_brew","mackis"),
    ("mackis","uncle_brew"),
    ("mackis","epson"),
    ("epson","mackis"),
    ("epson","bpi"),
    ("bpi","epson"),
    ("bpi","st_michaels"),
    ("st_michaels","bpi"),
    ("st_michaels","crown"),
    ("crown","st_michaels"),
    ("crown","pop_rock"),
    ("pop_rock","crown"),
    ("pop_rock","mayo_dia"),
    ("mayo_dia","pop_rock"),
    ("mayo_dia","sapp_ara"),
    ("sapp_ara","mayo_dia"),
    ("ncip","mshoes"),
    ("mshoes", "ncip"),
    ("mshoes", "mejia_bldg"),
    ("mejia_bldg", "mshoes"),
    ("mejia_bldg", "doc_uy"),
    ("doc_uy","mejia_bldg"),
    ("doc_uy","lanastida"),
    ("lanastida","doc_uy"),
    ("lanastida","tomntoms"),
    ("tomntoms","lanastida"),
    ("tomntoms","des_wing"),
    ("des_wing","tomntoms"),
    ("des_wing","icnhs"),
    ("icnhs","des_wing"),
    ("landbank","min_burger"),
    ("min_burger","landbank"),
    ("min_burger","mottrad_villa"),
    ("mottrad_villa","min_burger"),
    ("mottrad_villa","ncip"),
    ("ncip","mottrad_villa"),
    ("ncip","bpi"),
    ("bpi","ncip"),
    ("bpi","sec_bank"),
    ("sec_bank","bpi"),
    ("sec_bank","watsons"),
    ("watsons","sec_bank"),
    ("watsons","unitop"),
    ("unitop","watsons"),
    ("unitop","galaxy_mart"),
    ("galaxy_mart","unitop"),
    ("galaxy_mart","penshoppe"),
    ("penshoppe","galaxy_mart"),
    ("penshoppe","pnb"),
    ("pnb","penshoppe"),
    ("pnb","dnp"),
    ("dnp","pnb"),
    ("dnp","halal_meat"),
    ("halal_meat","dnp"),
    ("halal_meat","gaisano_old"),
    ("gaisano_old","halal_meat"),

    ("ball_4k","cq_print"),
    ("ortiz","citi_alley"),
    ("citi_alley","tomntoms"),
    ("zoey","gsis")
]

three_lanes = [
    ("vanitea","gaisano_mall")
    ("gaisano_mall","vanitea"),
    ("gaisano_mall","emcor"),
    ("emcor","gaisano_mall"),
    ("emcor","desmark"),
    ("desmark","emcor"),
    ("desmark","post_off"),
    ("post_off","desmark"),
    ("post_off","ncip"),
    ("ncip","post_off"),
    ("tc_circle","gaisano_old"),
    ("gaisano_old","tc_circle")
    ("pub_market","ukay_market"),
    ("ukay_market","dunkin"),
    ("dunkin","bike_ent"),
    ("bike_ent","pulis_agu"),
    ("pulis_agu","mc_hotel"),
    ("mc_hotel","pater"),
    ("pater","mot_race"),
    ("mot_race","zoey"),
    ("zoey","shoppe_24"),
    ("shoppe_24","ball_4k"),
    ("ball_4k","orix"),
    ("orix","crown"),
    ("crown","mejia_bldg"),
]

four_lanes = [
    ("mejia_bldg","coinsaver"),
    ("coinsaver","chandis"),
    ("chandis","meat_shop")
]

