landmarks = {
    # "iligan_pier":[("tc_circle", 113), ("coast_guard", 110)],
    # "tc_circle": [("iligan_pier", 113), ("daily", 261), ("gaisano_old", 193)],
    # "coast_guard": [("nehal_arc", 141)],
    # "daily": [("tc_circle", 261), ("coop_fuel", 190), ("fire_safe",117)],
    # "gaisano_old": [("nehal_arc", 50), ("ukay_market", 105), ("halal_meat", 114)],
    # "nehal_arc": [("gaisano_old", 50), ("wet_market", 37)],
    # "wet_market": [("pub_market", 112)],
    # "pub_market": [("ukay_market", 80)],
    # "ukay_market": [("dunkin", 113)],
    # "coop_fuel": [("daily", 190), ("octagon", 160 ), ("petron", 140)],

    "petron": [("coop_fuel", 140), ("uncle_brew", 170)],
    "coop_fuel": [("daily", 190), ("octagon", 160 ), ("petron", 140)],
    "daily": [("coop_fuel", 190), ("tc_circle", 261), ("fire_safe",117)],
    "tc_circle": [("daily", 261), ("iligan_pier", 113), ("gaisano_old", 193)],
    "iligan_pier":[("tc_circle", 113), ("coast_guard", 110)],
    "coast_guard": [("nehal_arc", 141)],
    "nehal_arc": [("gaisano_old", 50), ("wet_market", 37)],
    "gaisano_old": [("nehal_arc", 50), ("ukay_market", 105), ("halal_meat", 114)],
    "wet_market": [("pub_market", 112)],
    "pub_market": [("ukay_market", 80)],
    "ukay_market": [("dunkin", 113)],

    "uncle_brew": [("petron", 170), ("mackis", 50), ("emcor", 61)],
    "mackis": [("uncle_brew", 50), ("tita_fan", 40), ("epson", 50), ("desmark", 60)],
    "tita_fan": [("mackis", 40), ("avila_learn", 45)],
    "avila_learn": [("tita_fan", 45), ("frapella", 40), ("sec_bank", 94),],
    "frapella": [("avila_learn", 40), ("techtalk", 32)],
    "techtalk": [("frapella", 32), ("abest", 56)],
    "abest": [("techtalk", 56), ("octagon", 50)],
    "octagon": [("abest", 50), ("coop_fuel", 160), ("fire_safe", 95)], 
    "fire_safe": [("octagon", 95), ("daily", 117), ("rcbc", 45), ("pnb", 87)],      
}