landmarks = {
    #Petron Sabayle to Wet Market
    "petron": [("coop_fuel", 140), ("uncle_brew", 170)],
    "coop_fuel": [("daily", 190), ("octagon", 160 ), ("petron", 140)],
    "octagon": [("coop_fuel", 160)],
    "abest": [("octagon", 50)],
    "techtalk": [("abest", 56)],
    # "IS_Rep": ["fire_safe", "octagon"],
    "fire_safe": [("daily", 117), ("rcbc", 45), ("pnb", 87)],
    "daily": [("tc_circle", 261), ("coop_fuel", 190) ("fire_safe",117)],
    "tc_circle": [("iligan_pier", 113), ("daily", 261), ("gaisano_old", 193)],
    "iligan_pier":[("tc_circle", 113), ("coast_guard", 110)],
    "coast_guard": [("nehal_arc", 141)],
    # "Ludo": ["tc_circle", "gaisano_old"],
    "nehal_arc": [("wet_market", 37), ("gaisano_old", 50)],
    "gaisano_old": [("nehal_arc", 50), ("ukay_market", 105), ("halal_meat", 114)],
    "wet_market": [("pub_market", 112)],
    "pub_market": [("ukay_market", 80)],
    "ukay_market": [("dunkin", 113)],
    "halal_meat": [("gaisano_old", 144), ("dunkin", 97), ("dnp", 99)],
    "dnp": [("halal_meat", 99), ("rcbc", 45), ("bike_ent", 88)],
    "rcbc": [("dnp", 45), ("fire_safe", 89), ("penshoppe", 103)],
    # "agr_pharm": ["novo", "ukay_market", "dunkin"],
    # "novo": ["halal_meat", "gaisano_old", "agr_pharm"],
    # "Rojon": ["RCBC_PNB", "Penshoppe"], 
    "dunkin": [("bike_ent", 96)],
    "bike_ent": [("pulis_agu", 39)],
    "pulis_agu": [("pera_mpc", 40),("mc_hotel", 63)],
    "mc_hotel": [("pater", 46), ("learnfast", 47)],
    "pater": [("glo_flash", 47), ("penshoppe", 85), ("mot_race", 46)],
    "penshoppe": [("rcbc", 103), ("galaxy_mart", 46), ("pater", 85), ("octagon", 91)],
    "galaxy_mart": [("penshoppe", 46), ("unitop", 46)],   
    "learnfast": [("glo_flash", 46), ("tambacan", 78)],
    "glo_flash": [("learnfast", 46), ("tambacan", 43), ("red_carp", 48), ("pater", 47)],
    "red_carp": [("ilaya", 36), ("fount_acad", 44) ("mot_race", 47)],
    "ilaya": [("ortiz", 36), ("gsis", 40)],
    "gsis": [("fount_acad", 37), ("new_flash", 70)],
    "zoey": [("shoppe_24", 36), ("ilaya", 45)],
    "mot_race": [("red_carp", 47), ("zoey", 39)],
    "tambacan": [("glo_flash", 43), ("fount_acad", 48)],
    "fount_acad": [("red_carp", 44), ("tambacan", 48), ("gsis", 37)],
    "unitop": [("galaxy_mart", 46) ,("watsons", 33) , ("zoey", 85)],
    "pnb": [("dnp", 45), ("Pulis_Agu", 89), ("penshoppe", 102), ("fire_safe", 87)],
    "pera_mpc": [("learnfast", 59)],

    # Purok Concepcion
    "cq_print": [("coast_wat", 58), ("deja_teu", 37)],
    "ziga_teck": [("deja_teu", 58), ("sapp_ara", 44), ("pondoc", 59)],
    "deja_teu": [("ziga_teck", 58), ("icnhs", 45), ("cq_print", 37)],
    "coast_wat": [("cq_print", 58), ("ziga_teck", 40),("new_flash",58)],
    "new_flash": [("gsis", 70), ("coast_wat", 58), ("pondoc", 41)],
    "waynsee": [("pondoc", 48), ("orix", 46), ("pop_rock", 48)],
    "pondoc": [("new_flash", 41), ("ziga_teck", 59), ("mayo_dia", 47), ("waynsee", 48)],
    "mayo_dia": [("pondoc", 47), ("lanastida", 53), ("pop_rock", 45), ("sapp_ara", 64)],
    "sapp_ara": [("mayo_dia", 64), ("tomntoms", 57), ("icnhs", 60)],
    "icnhs": [("sapp_ara", 60), ("deja_teu", 45), ("des_wing", 58)],
    "ortiz": [("dexter", 36), ("shoppe_24", 48)],
    "dexter": [("news_flash", 47), ("waynsee", 40)],
    "shoppe_24": [("ball_4k", 38)],
    "ball_4k": [("dexter", 46), ("orix", 40)],
    "orix": [("waynsee", 46), ("crown", 47)],
    "crown": [("pop_rock", 46), ("mejia_bldg", 60), ("st_michaels", 37)],
    "pop_rock": [("doc_uy", 58), ("mayo_dia", 45), ("crown", 46)],
    "st_michaels": [("crown", 37), ("mshoes", 57), ("bpi", 47)],
    "bpi": [("st_michaels", 47), ("sec_bank", 88), ("ncip", 59), ("epson", 51)],
    "sec_bank": [("bpi", 88), ("ball_4k", 85), ("watsons", 40)],
    "watsons": [("sec_bank", 40), ("unitop", 33)],
    "epson": [("bpi", 51), ("mackis", 50), ("post_off", 58)],
    "mackis": [("tita_fan", 40), ("epson", 50), ("uncle_brew", 50)],
    "uncle_brew": [("mackis", 50), ("emcor", 61), ("petron", 170)],
    "tita_fan": [("avila_learn", 45)],
    # "tita_fan": [("mackis", 40), ("avila_learn", 45)],
    "avila_learn": [("sec_bank", 94), ("frapella", 40)],
    # "avila_learn": [("tita_fan", 45),("sec_bank", 94), ("frapella", 40)],
    "frapella": [("techtalk", 32)],
    # "frapella": [("avila_learn", 40), ("techtalk", )],
    # "cathedral": [("sec_bank", ), ("avila_learn", )],
    
    # National Road (GMall to ICNHS)
    "des_wing": [("icnhs", 58), ("tomntoms", 59)],
    "tomntoms": [("des_wing", 59), ("sapp_ara", 57), ("lanastida", 63)],
    "lanastida": ["tomntoms", "mayo_dia", "doc_uy"],
    "doc_uy": ["mejia_bldg", "lanastida", "pop_rock"],
    "mejia_bldg": ["mshoes", "crown", "doc_uy"],
    "mshoes": ["ncip", "st_michaels", "mejia_bldg"],
    "ncip": ["post_off", "bpi", "pbb", "mshoes"],
    "post_off": ["epson", "desmark", "ncip"],
    "desmark": [("mackis", 60), ("post_off", ), "emcor"],
    "emcor": ["desmark", "uncle_brew"], 

    # Palao Market
    "pbb": ["ncip", "kylas"],
    "phoenix_gas": ["Palao_Mrkt", "lanastida", "CoinSaver"],
    "CoinSaver": ["Chandis"],
    "kylas": ["pbb", "Alemania"],
    "Alemania": ["kylas", "MotTrad_Villa", "Bam_Doc"],
    "Chandis": ["MotTrad_Villa", "Meat_Shop", "Palao_Mrkt", "CoinSaver"],
    "MotTrad_Villa": ["Alemania", "Chandis", "Landbank"],
    "Bam_Doc": ["MercJupi_St", "Abund_Life"],
    "Palao_Mrkt": ["Chandis", "Ilgn_Deal", "Puregold"],
    "Ilgn_Deal": ["Palao_Mrkt", "COMELEC"],
    "COMELEC": ["Ilgn_Deal", "Puregold", "Megatech"],
    "Puregold": ["Palao_Mrkt", "Coco_Pet", "COMELEC"],
    "Megatech": ["Phoenix_LPG", "COMELEC", "Coco_Pet"],
    "Coco_Pet": ["Megatech", "Meat_Shop", "PC_Ilgn", "Puregold"],
    "Meat_Shop": ["Coco_Pet", "SYM", "Chandis"],
    "Landbank": ["MotTrad_Villa", "ColorChart"],
    "ColorChart": ["Landbank", "SYM"],
    "SYM": ["ColorChart", "Meat_Shop", "BDO_Network"],
    "BDO_Network": ["SYM", "PC_Ilgn"],
    "PC_Ilgn": ["BDO_Network", "Coco_Pet", "Phoenix_LPG"],
    "Phoenix_LPG": ["Megatech", "PC_Ilgn"]
}

# 3+ Lanes Roads (two-way)
    # Gaisano Mall to NCIP (6-lanes)
    # TC- Circle to Gaisano Old (6-lanes)
    # Co-op Fuel to TC-Circle (4-lanes)
    # NCIP to ICNHS (4-lanes)
    # Petron to Co-op Fuel (3-lanes)
    
# Two-Lane Roads
   
# Single-Lane Roads
    # Gaisano Mall to 