landmarks = {
    "petron": [("coop_fuel", 140), ("uncle_brew", 170)],
    "coop_fuel": [("daily", 190), ("octagon", 160 ), ("petron", 140)],
    "octagon": [("coop_fuel", 160)],
    "abest": [("octagon", 50)],
    "techtalk": [("abest", 56)],
    # "IS_Rep": ["fire_safe", "octagon"],
    "fire_safe": [("daily", 117), ("rcbc", 45), ("pnb", 87)],
    "daily": [("tc_circle", 261), ("coop_fuel", 190) ("fire_safe",117)],
    "tc_circle": [("iligan_pier", 113), ("daily", 261), ("gaisano_old", 193)],
    "iligan_pier":[("tc_circle", 113), ("coast_guard", 110)],
    "coast_guard": [("nehal_arc", 141)],
    # "Ludo": ["tc_circle", "gaisano_old"],
    "nehal_arc": [("wet_market", 37), ("gaisano_old", 50)],
    "gaisano_old": [("nehal_arc", 50), ("ukay_market", 105), ("halal_meat", 114)],
    "wet_market": [("pub_market", 112)],
    "pub_market": [("ukay_market", 80)],
    "ukay_market": [("dunkin", 113)],
    "halal_meat": [("gaisano_old", 144), ("dunkin", 97), ("dnp", 99)],
    "dnp": [("halal_meat", 99), ("rcbc", 45), ("bike_ent", 88)],
    "rcbc": [("dnp", 45), ("fire_safe", 89), ("penshoppe", 103)],
    # "agr_pharm": ["novo", "ukay_market", "dunkin"],
    # "novo": ["halal_meat", "gaisano_old", "agr_pharm"],
    # "Rojon": ["RCBC_PNB", "Penshoppe"], 
    "dunkin": [("bike_ent", 96)],
    "bike_ent": [("pulis_agu", 39)],
    "pulis_agu": [("pera_mpc", 40),("mc_hotel", 63)],
    "mc_hotel": [("pater", 46), ("learnfast", 47)],
    "pater": [("glo_flash", 47), ("penshoppe", 85), ("mot_race", 46)],
    "penshoppe": [("rcbc", 103), ("galaxy_mart", 46), ("pater", 85), ("octagon", 91)],
    "galaxy_mart": [("penshoppe", 46), ("unitop", 46)],   
    "learnfast": [("glo_flash", 46), ("tambacan", 78)],
    "glo_flash": [("learnfast", 46), ("tambacan", 43), ("red_carp", 48), ("pater", 47)],
    "red_carp": [("ilaya", 36), ("fount_acad", 44) ("mot_race", 47)],
    "ilaya": [("ortiz", 36), ("gsis", 40)],
    "gsis": [("fount_acad", 37)],
    "zoey": [("shoppe_24", 36), ("ilaya", 45)],
    "mot_race": [("red_carp", 47), ("zoey", 39)],
    "tambacan": [("glo_flash", 43), ("fount_acad", 48)],
    "fount_acad": [("red_carp", 44), ("tambacan", 48), ("gsis", 37)],
    "unitop": [("galaxy_mart", 46) ,("watsons", 33) , ("zoey", 85)],
    "pnb": [("dnp", 45), ("Pulis_Agu", 89), ("penshoppe", 102), ("fire_safe", 87)],
    "pera_mpc": [("learnfast", 59)],

    #Concepcion # Purok Concepcion
    "CQ_Print": ["Coast_Wat", "Deja_Teu"],
    "Coast_Wat": ["CQ_Print", "Ziga_Teck", "new_fash"],
    "new_fash": ["Coast_Wat", "Pondoc", "Dexter"],
    "Dexter": ["new_fash", "Ball_4k", "Waynsee", "ortiz"],
    "Ball_4k": ["Dexter", "Orix", "shoppe_24"],
    "ortiz": ["Dexter", "Ilaya", "shoppe_24"],
    "shoppe_24": ["Ball_4k", "Zoey", "ortiz"],
    "watsons": ["Sec_Bank", "Unitop"],
    "Frappella": ["techtalk", "Avila_Learn"],
    "Avila_Learn": ["Frappella", "Cathedral", "Tita_Fan"],
    "Cathedral": ["Sec_Bank", "Avila_Learn"],
    "Sec_Bank": ["BPI", "watsons", "Cathedral"],
    "Deja_Teu": ["Ziga_Teck", "ICNHS", "CQ_Print"],
    "ICNHS": ["Sapp_Ara", "Deja_Teu", "Des_Wing"],
    "Ziga_Teck": ["Deja_Teu", "Sapp_Ara", "Pondoc", "Coast_Wat"],
    "Pondoc": ["Ziga_Teck", "new_fash", "Mayo_Dia", "Waynsee"],
    "Waynsee": ["Pondoc", "Orix", "Pop_Rock", "Dexter"],
    "Orix": ["Ball_4k", "Waynsee", "Crown"],
    "Tita_Fan": ["Avila_Learn", "Mackis"],
    "uncle_brew": ["Emcor", "petron", "Mackis"],
    "Mackis": ["Tita_Fan", "Epson", "uncle_brew", "Desmark"],
    "Epson": ["Mackis", "BPI", "Post_Off"],
    "BPI": ["St_Michaels", "Sec_Bank", "NCIP", "Epson"],
    "St_Michaels": ["Crown", "MShoes", "BPI"],
    "Crown": ["Pop_Rock", "Orix", "Mejia_Bldg", "St_Michaels"],
    "Pop_Rock": ["Doc_Uy", "Mayo_Dia", "Waynsee", "Crown"],
    "Mayo_Dia": ["Pondoc", "Lanastida", "Pop_Rock", "Sapp_Ara"],
    "Sapp_Ara": ["Mayo_Dia", "TomNToms", "Ziga_Teck", "ICNHS"],
    "Des_Wing": ["ICNHS", "TomNToms"],
    "TomNToms": ["Des_Wing", "Lanastida", "Sapp_Ara"],
    "Lanastida": ["TomNToms", "Mayo_Dia", "Doc_Uy"],
    "Doc_Uy": ["Mejia_Bldg", "Lanastida", "Pop_Rock"],
    "Mejia_Bldg": ["MShoes", "Crown", "Doc_Uy"],
    "MShoes": ["NCIP", "St_Michaels", "Mejia_Bldg"],
    "NCIP": ["Post_Off", "BPI", "PBB", "MShoes"],
    "Post_Off": ["Epson", "Desmark", "NCIP"],
    "Desmark": ["Post_Off", "Mackis", "Emcor"],
    "Emcor": ["Desmark", "uncle_brew"], 
    
    #Gaisano_Mall
    "PBB": ["NCIP", "Kylas"],
    "Phoenix_Gas": ["Palao_Mrkt", "Lanastida", "CoinSaver"],
    "CoinSaver": ["Chandis"],
    "Kylas": ["PBB", "Alemania"],
    "Alemania": ["Kylas", "MotTrad_Villa", "Bam_Doc"],
    "Chandis": ["MotTrad_Villa", "Meat_Shop", "Palao_Mrkt", "CoinSaver"],
    "MotTrad_Villa": ["Alemania", "Chandis", "Landbank"],
    "Bam_Doc": ["MercJupi_St", "Abund_Life"],
    "Palao_Mrkt": ["Chandis", "Ilgn_Deal", "Puregold"],
    "Ilgn_Deal": ["Palao_Mrkt", "COMELEC"],
    "COMELEC": ["Ilgn_Deal", "Puregold", "Megatech"],
    "Puregold": ["Palao_Mrkt", "Coco_Pet", "COMELEC"],
    "Megatech": ["Phoenix_LPG", "COMELEC", "Coco_Pet"],
    "Coco_Pet": ["Megatech", "Meat_Shop", "PC_Ilgn", "Puregold"],
    "Meat_Shop": ["Coco_Pet", "SYM", "Chandis"],
    "Landbank": ["MotTrad_Villa", "ColorChart"],
    "ColorChart": ["Landbank", "SYM"],
    "SYM": ["ColorChart", "Meat_Shop", "BDO_Network"],
    "BDO_Network": ["SYM", "PC_Ilgn"],
    "PC_Ilgn": ["BDO_Network", "Coco_Pet", "Phoenix_LPG"],
    "Phoenix_LPG": ["Megatech", "PC_Ilgn"]
}